Demo/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Demo.Data.Dapper;
using Demo.Data.Domain;
using Extenso.Data.Entity;
using JQQueryBuilderHelpers;
using KendoGridBinder;
using KendoGridBinder.ModelBinder.Mvc;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;

namespace Demo.Controllers
{
    [Route("people")]
    public class PersonController : Controller, IJQQueryBuilderController
    {
        private readonly Lazy<IRepository<Person>> personRepository;
        private readonly Lazy<IRepository<SavedQuery>> savedQueryRepository;
        private readonly Lazy<IDapperRepository<Person, int>> personDapperRepository;

        public PersonController(Lazy<IRepository<Person>> personRepository,
            Lazy<IRepository<SavedQuery>> savedQueryRepository,
            Lazy<IDapperRepository<Person, int>> personDapperRepository)
        {
            this.personRepository = personRepository;
            this.savedQueryRepository = savedQueryRepository;
            this.personDapperRepository = personDapperRepository;
        }

        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            return View("Index");
        }

        [HttpPost]
        [Route("query")]
        public IActionResult Query(KendoGridMvcRequest request)
        {
            using (var connection = personRepository.Value.OpenConnection())
            {
                var query = connection.Query()
                    .OrderBy(x => x.FamilyName)
                    .ThenBy(x => x.GivenNames);

                var grid = new KendoGrid<Person>(request, query);
                return Json(grid);
            }
        }

        [HttpPost]
        [Route("execute-query")]
        public IActionResult ExecuteQuery([FromBody] JQQueryBuilderRawQuery query)
        {
            try
            {
                int count = personDapperRepository.Value.Count(query.Query);
                if (count > 0)
                {
                    var data = personDapperRepository.Value.Find(query.Query, query.Skip, query.Take);
                    var grid = new KendoGrid<Person>(data, count);
                    return Json(grid);
                }
                else
                {
                    return Json(new KendoGrid<Person>(Enumerable.Empty<Person>(), 0));
                }
            }
            catch (Exception x)
            {
                return Json(new { Success = false, Message = x.GetBaseException().Message });
            }
        }

        #region IJQQueryBuilderController Members

        [HttpGet]
        [Route("get-query-config")]
        public IActionResult GetQueryConfig()
        {
            var jqQueryBuilderConfig = new JQQueryBuilderConfig
            {
                // Bootstrap 4 is not supported yet. See more at: https://github.com/mistic100/jQuery-QueryBuilder/issues/432...
                //Plugins = JQQueryBuilderConfig.DefaultPlugins.Value,

                //  ... so for now, let's use the following plugins only.
                Plugins = new Dictionary<string, object>
                {
                    { "sortable", null },
                    { "unique-filter", null },
                    { "invert", null },
                    { "not-group", null },
                    { "sql-support", JObject.FromObject(new { boolean_as_integer = false }) }
                },
                Filters = new List<JQQueryBuilderFilter>
                {
                    new JQQueryBuilderFilter { Id = "family-name", Field = "\"FamilyName\"" , Label = "Family Name", Operators = JQQueryBuilderConfig.ShortTextOperatorTypes.Value},
                    new JQQueryBuilderFilter { Id = "given-names", Field = "\"GivenNames\"", Label = "Given Name/s", Operators = JQQueryBuilderConfig.ShortTextOperatorTypes.Value },

                    new JQQueryBuilderFilter
                    {
                        Id = "date-of-birth",
                        Field = "\"DateOfBirth\"",
                        Label = "Date of Birth",
                        Operators = JQQueryBuilderConfig.DateTimeOperatorTypes.Value,
                        Plugin = "datepicker",
                        PluginConfig = new
                        {
                            format = "yyyy-mm-dd",
                            todayBtn = "linked",
                            todayHighlight = true,
                            autoclose = true
                        }
                    }
                }
            };
            return Json(jqQueryBuilderConfig);
        }

        [HttpGet]
        [Route("load-query/{key}")]
        public async Task<IActionResult> LoadQuery(Guid key)
        {
            var savedQuery = await savedQueryRepository.Value.FindOneAsync(key);
            return Json(savedQuery);
        }

        [HttpPost]
        [Route("save-query")]
        public async Task<IActionResult> SaveQuery([FromBody] JQQueryBuilderSavedQuery query)
        {
            try
            {
                var savedQueryEntityType = SavedQueryEntityType.Person;

                var savedQuery = await savedQueryRepository.Value.FindOneAsync(x => x.Type == savedQueryEntityType && x.Name == query.Name);

                var isNew = false;
                if (savedQuery == null)
                {
                    isNew = true;
                    savedQuery = new SavedQuery
                    {
                        Type = savedQueryEntityType,
                        Name = query.Name,
                        Query = query.Query,
                    };
                    await savedQueryRepository.Value.InsertAsync(savedQuery);
                }
                else
                {
                    savedQuery.Query = query.Query;
                    await savedQueryRepository.Value.UpdateAsync(savedQuery);
                }

                return Json(new { Success = true, QueryId = savedQuery.Id, Name = savedQuery.Name, IsNew = isNew });
            }
            catch (Exception x)
            {
                return Json(new { Success = false, Message = x.GetBaseException().Message });
            }
        }

        #endregion IJQQueryBuilderController Members
    }
}

Demo/Controllers/SavedQueryController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Demo.Data.Domain;
using Extenso;
using Extenso.Data.Entity;
using KendoGridBinder;
using KendoGridBinder.ModelBinder.Mvc;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Controllers
{
    [Route("saved-queries")]
    public class SavedQueryController : Controller
    {
        private readonly Lazy<IRepository<SavedQuery>> repository;

        public SavedQueryController(Lazy<IRepository<SavedQuery>> repository)
        {
            this.repository = repository;
        }

        [Route("")]
        public IActionResult Index(string entityType)
        {
            ViewBag.EntityType = entityType;
            return View("Index");
        }

        [HttpPost]
        [Route("query/{entityType}")]
        public IActionResult Query(string entityType, [FromBody]KendoGridMvcRequest request)
        {
            using (var connection = repository.Value.OpenConnection())
            {
                var type = EnumExtensions.Parse<SavedQueryEntityType>(entityType);

                var query = connection.Query(x => x.Type == type)
                    .OrderBy(x => x.Name)
                    .ThenBy(x => x.Name);

                var grid = new KendoGrid<SavedQuery>(request, query);
                return Json(grid);
            }
        }

        [HttpGet]
        [Route("delete/{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            await repository.Value.DeleteAsync(x => x.Id == id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("edit/{id}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var product = await repository.Value.FindOneAsync(id);
            return View(product);
        }

        [HttpPost]
        [Route("update")]
        public async Task<IActionResult> Update(SavedQuery model)
        {
            var product = await repository.Value.FindOneAsync(model.Id);
            product.Name = model.Name;
            //product.Query = model.Query;

            await repository.Value.UpdateAsync(product);

            return Json(new { status = true, redirectUrl = Url.Action("Index") });
        }
    }
}

Demo/Views/Person/Index.cshtml
@using System.Globalization
@using Demo.Data.Domain

@{
    ViewBag.Title = "People";

    string rtlClass = string.Empty;

    if (CultureInfo.CurrentCulture.TextInfo.IsRightToLeft)
    {
        rtlClass = "k-rtl";
    }
}

<div id="grid-section" class="row">
    <section class="col-md-12">
        <div class="card">
            <div class="card-header text-white bg-dark mb-3">Query Builder</div>
            <div class="card-body">
                <section>
                    <div class="col-md-12">
                        <form class="form-inline">
                            <div class="form-group">
                                @Html.ThisApp().SavedQueryDropDownList("SelectedQuery", SavedQueryEntityType.Person, htmlAttributes: new { @class = "form-control" })
                            </div>
                            <button type="button" class="btn btn-primary" data-bind="click: loadQuery">
                                <i class="fa fa-folder-open-o"></i>
                                Load
                            </button>
                        </form>
                    </div>
                </section>
                <section class="clearfix">
                    <div class="col-md-12">
                        <div id="query-builder"></div>

                        <button class="btn btn-primary" data-bind="click: runQuery">
                            <i class="fa fa-play"></i>
                            Execute
                        </button>
                        <button class="btn btn-warning" data-bind="click: resetQuery">
                            <i class="fa fa-sync-alt"></i>
                            Reset
                        </button>
                        <button class="btn btn-success" data-bind="click: openSaveQueryDialog">
                            <i class="fa fa-save"></i>
                            Save Query
                        </button>
                        <a class="btn btn-secondary" href="@Url.Action("Index", "SavedQuery", new { entityType = "Person" })">
                            <i class="fa fa-tasks"></i>
                            Manage Queries
                        </a>
                    </div>
                </section>
            </div>
        </div>
    </section>
    
    <section class="col-md-12">
        <div class="card">
            <div class="card-header text-white bg-dark mb-3">Grid</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <button data-bind="click: create" class="btn btn-primary">
                            <i class="fa fa-plus"></i>
                            Create
                        </button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 @rtlClass">
                        <div id="grid"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<div id="form-section" class="row" style="display:none">
    <article class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Details</h5>

                <form id="form-section-form" role="form" class="form-horizontal">
                    <fieldset>
                        <legend id="form-section-legend"></legend>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    @Html.Label("FamilyName", "Family Name", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-3" })
                                    <div class="col-xs-12 col-sm-8 col-md-9 col-lg-9">
                                        <input name="FamilyName" type="text" class="form-control" data-bind="value: familyName" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    @Html.Label("GivenNames", "Given Name/s", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-3" })
                                    <div class="col-xs-12 col-sm-8 col-md-9 col-lg-9">
                                        <input name="GivenNames" type="text" class="form-control" data-bind="value: givenNames" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    @Html.Label("DateOfBirth", "Date of Birth", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-3" })
                                    <div class="col-xs-12 col-sm-8 col-md-9 col-lg-9">
                                        <input id="DateOfBirth" name="DateOfBirth" type="text" class="form-control" data-bind="value: dateOfBirth" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group pull-right">
                            <div class="col-md-12">
                                <button type="button" class="btn btn-default" data-bind="click: cancel">Cancel</button>
                                <button type="button" class="btn btn-primary" data-bind="click: save"><i class="fa fa-save"></i> Save</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </article>
</div>

<div id="saveQueryModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Save Query</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form role="form" class="form-horizontal">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.Label("Query_Name", "Name", new { @class = "control-label" })
                                @Html.TextBox("Query_Name", null, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" data-bind="click: saveQuery"><i class="fa fa-save"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script type="text/javascript">
        var currentSection = $("#grid-section");

        function switchSection(section) {
            if (section.attr("id") == currentSection.attr("id")) {
                return;
            }
            currentSection.hide("fast");
            section.show("fast");
            currentSection = section;
        };
    </script>

    <script src="~/js/app/people.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            viewModel = new ViewModel();
            ko.applyBindings(viewModel);
            viewModel.init();
        });
    </script>
}